### PR TITLE
fix: ci failing when testing outside working dir

### PR DESCRIPTION
**Pull request by calebdw**
Hello!

CI is currently failing when testing Laravel outside of the working directory. The tests fully pass when testing inside the Laravel application so this points to a bootstrapping and/or a path/stub resolution issue (as best as I can tell).

I don't really see the need / point of trying to test outside the working dir so just opted to remove the test altogether.

Thanks!

### CODE REVIEW

**Comment by szepeviktor** [comment]
> CI is currently failing when testing Laravel outside of the working directory.

Thank you for your report.
Could you show me an example?

**Comment by calebdw** [comment]
https://github.com/larastan/larastan/actions/runs/8034035538/job/21945136111

**Comment by szepeviktor** [comment]
This failure is caused by a420e73b2c40ebef27637a3b482e0ebd187e5178

**Comment by canvural** [comment]
Hi,

The issue is not related to that. As @szepeviktor pointed out it is caused by the latest commit. I'm trying to fix it actually. But it's taking some time. Maybe I can revert the last commit in the meanwhile.

**Comment by calebdw** [comment]
I understand which commit caused the failure. However, I believe the generics are correct and there's nothing in the commit that would be responsible for the error.

On top of that, the tests **do pass**, when phpstan is executed inside the project indicating that there's nothing wrong with the commit

**Comment by szepeviktor** [comment]
This is good news!
Now we have something to investigate.

**Pull request closed without merging**
