### PR TITLE
feat: adds conditional return types to some global helper functions

### PR DESCRIPTION
**Pull request by canvural**
- [x] Added or updated tests
- [ ] Documented user facing changes
- [ ] Updated CHANGELOG.md

**Changes**

This PR adds conditional return types to some global helper functions. Replaces some of the existing extensions we have.

**Breaking changes**
n/a

### CODE REVIEW

**Comment by paras-malhotra** [comment]
@canvural, I believe with this PR, it is not possible to change stubs. So, if I have a `Request.stub` file in my project, it will still pick up the `Request.stub` file from Larastan.

Related: #1265

**Comment by szepeviktor** [comment]
Could you share your stub and the relevant config lines?

**Comment by paras-malhotra** [comment]
Here is the stub: https://github.com/enlightn/enlightn/blob/1937be5e6bd3142dfd03de90927ddd571f16477c/stubs/Request.stub

And the config lines: https://github.com/enlightn/enlightn/blob/1937be5e6bd3142dfd03de90927ddd571f16477c/phpstan.neon#L19-L20

**Comment by szepeviktor** [comment]
Is it okay if you overwrite `vendor/nunomaduro/larastan/stubs/Http/Request.stub` ?
`phpstan clear-result-cache` first!

**Comment by paras-malhotra** [comment]
@szepeviktor, yes it does. Overwriting the Larastan `Request.stub` file succeeds in the latest version of Larastan

**Comment by szepeviktor** [comment]
The answer is here: https://github.com/nunomaduro/larastan/issues/1265#issuecomment-1147124799

**Comment by paras-malhotra** [comment]
Sure, thanks. I opened https://github.com/phpstan/phpstan/issues/7461

**Comment by szepeviktor** [comment]
> I opened [phpstan/phpstan#7461](https://github.com/phpstan/phpstan/issues/7461)

`cp -f Your.stub Larastan.stub` :(

**Comment by paras-malhotra** [comment]
Can we not go back to the `stubFiles` configuration in Larastan rather than using a custom `stubFilesExtension`? It will fix this change in behaviour.

**Comment by szepeviktor** [comment]
@canvural can tell that.

**Comment by szepeviktor** [comment]
@paras-malhotra HAve you tried pushing in your custom stabs file by `stubFilesExtension`?

**Comment by paras-malhotra** [comment]
> @paras-malhotra Have you tried pushing in your custom stubs file by `stubFilesExtension`?

No, I haven't tried that yet. I am assuming you mean adding a `stubFilesExtension` service in Enlightn?

[This code](https://github.com/phpstan/phpstan-src/blob/943d95ee3c36ade6233e66b92591dac08af634dc/src/PhpDoc/DefaultStubFilesProvider.php#L38-L43) seems to just append the stub files from all extensions, so I'm not sure that would work.

**Comment by canvural** [comment]
Hi,

Multiple stub file for one class were never supported by PHPStan. So in previous versions your code was working "by accident"

> Can we not go back to the stubFiles configuration in Larastan rather than using a custom stubFilesExtension?

Stubs in Larastan are growing. Using `stubFiles` we'd had to keep `extension.neon` in sync with the new stubs. I do not want to maintain that anymore. `stubFilesExtension` seemed like a good solution.

On the other hand maybe we can go back to it if [this](
https://github.com/phpstan/phpstan/issues/4342) is implemented.

**Pull request merged**
