### PR TITLE
Move Laravel test to a script

### PR DESCRIPTION
**Pull request by szepeviktor**
Fix #48

### CODE REVIEW

**Comment by nunomaduro** [comment]
I am gonna wait a bit, to see if the travis goes green on this one. 😅

**Comment by szepeviktor** [comment]
Could you help me run Larastan from bare files?
Seem like the composer `vcs = ../` does not work as Travis does not have git files.

**Comment by nunomaduro** [comment]
@szepeviktor I need to sleep today. I will take a look at this tomorrow night! 😴

**Comment by nunomaduro** [comment]
Great job! Thanks! 👏

**Pull request merged**
