### PR TITLE
[wip] feature: inspect eloquent where method parameters

### PR DESCRIPTION
**Pull request by mr-feek**
I had some time to work on closing #472.

This is a pretty solid starting point, and I'll continue working on it as I have time. Feel free to branch off of if if you are interested.

### CODE REVIEW

**Comment by mr-feek** [comment]
It's quite difficult to test that this properly catches failures until the testsuite is updated to support expected failure cases.

**Comment by canvural** [comment]
Thank you for your time for this! But I was also working on this :sweat_smile: That's why I assigned the issue to myself.

**Comment by mr-feek** [comment]
Sorry, last I saw was this 

> just thinking how valuable it'd be before spending time to implement it 🤔

Any value in me continuing this or did you get further?

**Comment by canvural** [comment]
I appreciate the time you put into this, but like I said I was also working on this. Sorry for the confusion I thought assigning the issue to myself would be enough to indicate I'm working on it. Maybe we need a new label for this :smile: 

So, I am closing this.

**Comment by mr-feek** [comment]
I think you need to work on your communication and collaboration skills @canvural .

You have many issues assigned to yourself. I don't think I'll be helping to contribute anymore.

Good luck

**Pull request closed without merging**
