### PR TITLE
Add information about ignoring errors

### PR DESCRIPTION
**Pull request by olivernybroe**
- [ ] Added or updated tests
- [ ] Documented user facing changes
- [x] Updated CHANGELOG.md

**Changes**
Just added some information to the README file about ignoring errors and baseline files

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thank you for your contribution.

Do we really want to have a truncated copy of https://phpstan.org/user-guide/ignoring-errors ?

**Comment by olivernybroe** [comment]
@szepeviktor Not entirely sure if we want it 😄 @nunomaduro just asked me to PR it. 

I think the thought was that many users of Larastan prob. won't bother reading phpstan docs and just think that they cannot do this kinda stuff 👍

**Comment by szepeviktor** [comment]
Walking stick for working-faster-than-possible people?
Okay I'm out.

**Comment by szepeviktor** [comment]
This PR will never get merged: https://github.com/nunomaduro/larastan/pull/876/files
Many of us chase popularity.

**Comment by olivernybroe** [comment]
@szepeviktor haha I like that solution 👍

**Pull request merged**
