### PR TITLE
Say goodbye to orchestra/testbench

### LINKED ISSUE #295: Improvement: remove orchestra dependency
The addition of the `orchestra` dependency cause too many issues. https://github.com/nunomaduro/larastan/issues/259 https://github.com/nunomaduro/larastan/pull/247 and many others.

**Goal**: 

1. Remove the dependency `orchestra/testbench` here.
2. Add the dependency `orchestra/testbench` to the suggest on composer, and update the readme explaining if you are using `larastan` for packages you need to install this dependency.

> After this feature we need to release a major version.

### PR DESCRIPTION
**Pull request by szepeviktor**
Closes #295

### CODE REVIEW

**Comment by nunomaduro** [comment]
Thanks for this @szepeviktor, I believe we should also adjust the readme. Can you write a section? Saying that for packages, the developer should install the package...

**Comment by szepeviktor** [comment]
In the _Usage in Packages for Laravel_ section?

**Comment by nunomaduro** [comment]
Exactly buddy.

**Comment by szepeviktor** [comment]
Done.

**Comment by nunomaduro** [comment]
@szepeviktor We should have targeted a `develop` branch for this. As will be shipped on the next major version.

**Comment by szepeviktor** [comment]
Do we have a develop branch?
https://github.com/nunomaduro/larastan/branches

**Comment by szepeviktor** [comment]
If I create one may I remove these commits from master?

**Comment by nunomaduro** [comment]
It's fine, give me some time to prepare a new version. I am looking a some issues that I can close easily before the major version.

**Pull request merged**
