### PR TITLE
PHP 7.4 compatibility

### PR DESCRIPTION
**Pull request by kylekatarnls**

### CODE REVIEW

**Comment by nunomaduro** [comment]
Can you update the pr?

**Comment by kylekatarnls** [comment]
Done. As @szepeviktor noticed here: https://github.com/nunomaduro/larastan/pull/303#issuecomment-524656377

There is an other problem to solve in/around ServiceProvider.php.

**Comment by kylekatarnls** [comment]
This incompatibility is not yet fixed by Laravel, it needs:
https://github.com/laravel/framework/pull/29482 + https://github.com/driesvints/framework/pull/1

**Comment by kylekatarnls** [comment]
Meanwhile we may add an empty view config in tests so `$this->app->config['view']` would be an array and the errors would not be raised.

**Comment by kylekatarnls** [comment]
Fixed. So no matter Lumen will be compatible to PHP 7.4, we can check than larastan itself is now.

**Comment by nunomaduro** [comment]
Thanks!

**Pull request merged**
