### PR TITLE
Import all global functions

### PR DESCRIPTION
**Pull request by mad-briller**
- [x] Added or updated tests
- [x] Documented user facing changes

**Changes**
Adds `use function` for all global functions used in the extension, this reduces the overhead of calls and gives opcache more opportunities to optimize

... just waiting for styleci to send me a patch to format it correctly :sweat_smile:

### CODE REVIEW

**Review by szepeviktor — APPROVED** [review]
Very good job!

**Comment by szepeviktor** [comment]
Could you add a rule enforcing it to StyleCI configuration?
https://cs.symfony.com/doc/rules/import/global_namespace_import.html

**Comment by mad-briller** [comment]
the project does not have a local setup for phpcs, and instead uses the `laravel` preset of styleci to enforce coding standards
i'm not at all familiar with styleci, thought i imagine it's possible

**Comment by szepeviktor** [comment]
> and instead uses the `laravel` preset of styleci

I am looking it up for you 🏃🏻 
https://docs.styleci.io/configuration#default-configuration

**Comment by szepeviktor** [comment]
`/.styleci.yml`

```yaml
preset: laravel
enabled:
  - global_namespace_import:
    - import_classes: true
    - import_constants: false
    - import_functions: true
```

Docs says this is not possible.
https://docs.styleci.io/fixers
@GrahamCampbell Could you help us?

**Comment by sanfair** [comment]
Hello, I found that StyleCI has [`native_function_invocation`](https://docs.styleci.io/fixers#native_function_invocation)

So we can update the config like so:
```yml
preset: laravel
risky: true
enabled:
  - native_function_invocation
```

I tried it and it added a leading slash to internal functions in the global namespace (https://github.styleci.io/analyses/ne1YaN)
However, the calls to the user functions have not changed

And it won't work with suggested changes. This way the code will look a little messy in my opinion (https://github.styleci.io/analyses/ma5OVK)

**Comment by canvural** [comment]
If StyleCI is fine with it for now, it's enough. We can find a solution for new code, later.

Thank you!

**Pull request merged**
