### PR TITLE
fix: Carbon v3 macro reflection

### PR DESCRIPTION
**Pull request by calebdw**
Hello!

Carbon v3 switched from a static property to an instance property: https://github.com/briannesbitt/Carbon/commit/a12231089585d602c01bb4efa7c25f10bdbad0e2

This PR updates the macro extension to handle this change and should fix the pipeline.

Thanks!

### CODE REVIEW

**Comment by calebdw** [comment]
Why can the global `CARBON_VERSION` constant not be found? 

PHPStan v1.7.0 claims that nothing special is needed, but it's still defined in the bootstrap file anyways...
https://phpstan.org/user-guide/discovering-symbols#global-constants

**Comment by calebdw** [comment]
Another thing to consider is that we might not have to support Carbon macros because Carbon publishes an `extension.neon` for their macros which is automatically installed when using the [phpstan/extension-installer](https://github.com/phpstan/extension-installer)

**Comment by CanVuralStudocu** [comment]
Oops, I did not see this and fixed the same issue here: https://github.com/larastan/larastan/commit/6fb6803c039cdd163a657fad6758257b45f187de

> Another thing to consider is that we might not have to support Carbon macros because Carbon publishes an extension.neon for their macros which is automatically installed when using the [phpstan/extension-installer](https://github.com/phpstan/extension-installer)
That's something to consider for the future. Not sure if it does the same things exactly.

**Comment by canvural** [comment]
Oops, I did not see this and fixed the same issue here: https://github.com/larastan/larastan/commit/6fb6803c039cdd163a657fad6758257b45f187de

> Another thing to consider is that we might not have to support Carbon macros because Carbon publishes an extension.neon for their macros which is automatically installed when using the [phpstan/extension-installer](https://github.com/phpstan/extension-installer)

That's something to consider for the future. Not sure if it does the same things exactly.

**Pull request closed without merging**
