### PR TITLE
refactor: tidy up command line in tests

### LINKED ISSUE #681: Unit test problem on MINGW64
Laravel version: master

### Description
I just fork this repo and run composer test on master branch. I got a fail test for my PHPUnit. I already run composer install. Is there anything that I'm doing wrongly?

image

I'm using windows 10. PHP 7.4.5

### PR DESCRIPTION
**Pull request by szepeviktor**
1. introduce dirname
1. proper CLI options
1. indent code
1. support Windows

Fixes #681

### CODE REVIEW

**Comment by szepeviktor** [comment]
@xitox97 Please run `php path\to\composer run-script test:unit`

**Comment by canvural** [comment]
Hi,

Thank you very much for digging into this issue!

Using the `dirname` function is for supporting Windows? If so can you also change the usages in `tests/Rules` folder? For example here: https://github.com/nunomaduro/larastan/blob/master/tests/Rules/ModelPropertyRuleTest.php#L13 I believe this will fix the rest of the errors @xitox97 getting

**Comment by szepeviktor** [comment]
> Using the `dirname` function is for supporting Windows?

No, there are several forward slashes in  several paths causing no problems.
Using real PHPStan path `/vendor/phpstan/phpstan/phpstan` makes Windows work.
`/vendor/bin/phpstan/` is a shell script on Windows thus php.exe cannot execute it.

**Review by canvural — APPROVED** [review]

**Comment by canvural** [comment]
Thank you!

**Pull request merged**
