### PR TITLE
fix: Collection::random with model

### LINKED ISSUE #1626: Collection::random return type incorrect for TValue of Model
- Larastan Version: 2.5.1
- `--level` used: 6
- Pull request with failing test: #1627 

### Description

The return type for `Illuminate\Support\Collection::random()` is incorrect when `TValue` is subtype of `Model`.  Instead of being `TValue`, it is `Illuminate\Support\Collection`:

Code:
```php
        $c = collect([new \App\Models\User()]);
        \PHPStan\dumpType($c);
        \PHPStan\dumpType($c->random());
```

Result:
```
  31     Dumped type: Illuminate\Support\Collection<int, App\Models\User>
  32     Dumped type: Illuminate\Support\Collection
```

This issue only seems to present when `TValue` is a subtype of `Model`.  Unions comprised of `Model` subtypes with other types seem to work as expected:

Code:
```php
        $c = collect([new \App\Models\User(), 123]);
        \PHPStan\dumpType($c);
        \PHPStan\dumpType($c->random());
```

Result:
```
  28     Dumped type: Illuminate\Support\Collection<int, App\Models\User|int>
  29     Dumped type: App\Models\User|int
```

### PR DESCRIPTION
**Pull request by drrcknlsn**
Failing test for issue #1626 

fixes #1626

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thank you.

**Comment by drrcknlsn** [comment]
This may be the fix, as it passes the test and doesn't regress any others, but I'm not sure:
```
--- a/src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php
+++ b/src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php
@@ -75,7 +75,7 @@ class CollectionGenericStaticMethodDynamicMethodReturnTypeExtension implements D
         $classReflection = $calledOnType->getObjectClassReflections()[0];

         // Special cases for methods returning single models
-        if ($classReflection->getName() === EloquentCollection::class && (new ObjectType(Model::class))->isSuperTypeOf($returnType)->yes()) {
+        if (($classReflection->getName() === EloquentCollection::class || $classReflection->getName() === Collection::class) && (new ObjectType(Model::class))->isSuperTypeOf($returnType)->yes()) {
             return $returnType;
         }
```

**Comment by canvural** [comment]
@drrcknlsn If it doesn't cause any other test to break, that looks like an ok solution. Please update the PR with that, and we'll see.

**Review by canvural — APPROVED** [review]
Looks all good 👍🏽

**Pull request merged**
