### PR TITLE
feat: added auto discovery providers by composer.json

### PR DESCRIPTION
**Pull request by lxShaDoWxl**
- [ ] Added or updated tests
- [ ] Documented user facing changes
- [ ] Updated CHANGELOG.md

**Changes**
Load provider by composer config in sub packages
support this
```json
"extra": {
      "laravel": {
          "providers": [
              "\\Package\\ServiceProvider"
          ]
      }
},
```

**Breaking changes**

### CODE REVIEW

**Comment by szepeviktor** [comment]
Hello Viktor! This is Viktor here :)

You are struck by  #1115

**Comment by szepeviktor** [comment]
Thank you!
Could you give package names?

**Comment by lxShaDoWxl** [comment]
sorry my packages private in organization(
example
fitst package 
https://github.com/PHP-Open-Source-Saver/jwt-auth
the second private package with required PHP-Open-Source-Saver/jwt-auth

**Comment by lxShaDoWxl** [comment]
if necessary I can create sample packages

**Comment by canvural** [comment]
This is fixed in the latest commits.

**Pull request closed without merging**
