### PR TITLE
Add .github folder to the export-ignore list

### PR DESCRIPTION
**Pull request by dingo-d**
- [ ] Added or updated tests (no tests needed)
- [ ] Documented user facing changes (no user facing changes, just a slimmer release)
- [ ] Updated CHANGELOG.md

**Changes**

Added `.github` folder to the `.gitattributes` so that it's not copied over when people require the package.

No breaking changes. Not sure if I need to update the changelog or if this will be done when a new release is made 🤷🏼‍♂️

### CODE REVIEW

**Comment by szepeviktor** [comment]
Sparing 1 KB, Denis!

**Comment by dingo-d** [comment]
Seeing how this package has (currently) 4 086 874 installs, I'd say it adds up 😉

**Comment by williamdes** [comment]
Very good contribution !

You could also remove `phpstan.neon.dist` ;)

**Comment by dingo-d** [comment]
Ufff forgot about that one. Can you make a PR? I can do it, not a big problem, but since you've noticed it 😄

**Comment by williamdes** [comment]
> Ufff forgot about that one. Can you make a PR? I can do it, not a big problem, but since you've noticed it 😄

Go ahead you will be quicker than me 😄

**Pull request merged**
