### PR TITLE
Use Guard contract directly rather than trying to resolve it.

### PR DESCRIPTION
**Pull request by CyberiaResurrection**
Trying to resolve an issue @canvural tripped over in #338 - user code running when it shouldn't be.

### CODE REVIEW

**Comment by canvural** [comment]
What about [this] (https://github.com/nunomaduro/larastan/blob/master/tests/Features/ReturnTypes/AuthExtension.php#L22) test?

**Comment by CyberiaResurrection** [comment]
@canvural , https://github.com/nunomaduro/larastan/blob/8017aa4f6436618172158e118f58936e43973470/tests/Features/ReturnTypes/Helpers/AuthExtension.php ?

**Comment by canvural** [comment]
Yes, you changed the test for `auth` helper function. Doesn't the `Auth` facade test needs changing?

**Comment by CyberiaResurrection** [comment]
Good catch - thank you.

**Comment by szepeviktor** [comment]
Larastan flies with a never before seen speed.

# ✈️ 

@nunomaduro

**Pull request merged**
