### PR TITLE
Handle "cookie()" helper function

### LINKED ISSUE #59: Call to an undefined method forever().
```
$response->withCookie(cookie()->forever('name', 'value'));
```
Produce:
> Call to an undefined method Illuminate\Cookie\CookieJar|Symfony\Component\HttpFoundation\Cookie::forever().

### PR DESCRIPTION
**Pull request by ForzaSFerrari**
Fixes #59

### CODE REVIEW

**Comment by szepeviktor** [comment]
@ForzaSFerrari Thank you.
Does it work for you?

**Comment by szepeviktor** [comment]
@ForzaSFerrari Could you switch your editor to LF line ends and force-push your commit?

**Comment by nunomaduro** [comment]
Thank you @ForzaSFerrari!

**Comment by nunomaduro** [comment]
@szepeviktor For coding style issues it's kind of fine. We do use StyleCI for those things.

**Comment by szepeviktor** [comment]
OK, I consider using LF a benefit for everyone.

**Pull request merged**
