### PR TITLE
feat: laravel 10 support

### PR DESCRIPTION
**Pull request by nunomaduro**
This pull request is a work in progress and it adds Laravel 10 support to Larastan.

### CODE REVIEW

**Comment by nunomaduro** [comment]
@canvural Any ideas why the static analysis workflow is failing?

**Comment by szepeviktor** [comment]
https://github.com/laravel/framework/blob/10.x/src/Illuminate/Auth/SessionGuard.php#L30

That class does exist.

**Comment by canvural** [comment]
I had the same issue in https://github.com/nunomaduro/larastan/pull/1503

I have no idea why it can't find the class. But converting `SessionGuard::class` to `'Illuminate\Auth\SessionGuard'`, works.

**Comment by szepeviktor** [comment]
> fix: missing class

Could we open an issue for that?

**Comment by nunomaduro** [comment]
@canvural Merging this - feel free to provide feedback if necessary.

**Comment by canvural** [comment]
@nunomaduro  I just had the time to look at it. Looks good to me 👍🏽  Thanks.

**Pull request merged**
