### PR TITLE
fix: PHPStan 1.9.0 compatibility

### PR DESCRIPTION
**Pull request by canvural**
This PR adds PHPStan 1.9.x compatibility.

### CODE REVIEW

**Comment by agi--** [comment]
Is it possible to apply that patch also to 1.0.3? We still need to use that version because we haven't yet switched to Laravel 9.x.

**Comment by canvural** [comment]
No. 1.x releases are not maintained any more. It lacks a lot of fixes, not just this one. 

You can use your own fork with this fix though.

**Comment by agi--** [comment]
Ok, we can do that, but I think the better approach would be to upgrade Laravel as soon as possible. Thanks for the fast reply.

**Comment by NickStallman** [comment]
I've also got a few Laravel 8 projects and I'm hitting this issue. It would be appreciated if it could be backported, or at least make Larastan 1.x block PHPStan 1.9 so it doesn't completely break.

**Comment by szepeviktor** [comment]
@NickStallman Hello! Thank you for commenting.
Please add `"phpstan/phpstan": "< 1.9",` to your Composer configuration.

**Pull request merged**
