### PR TITLE
feat: add laravel and php version to issue template

### PR DESCRIPTION
**Pull request by calebdw**
Hello!

This just adds the Laravel and PHP version to the issue template as that can provide valuable context.

Thanks!

### CODE REVIEW

**Comment by szepeviktor** [comment]
I would gladly ask people for Laravel version on a case-by-case basis.

**Comment by calebdw** [comment]
Is there any reason to not just ask for it in the template?

**Comment by szepeviktor** [comment]
I don't make decisions here.
I think filling in fields annoys people.

**Comment by canvural** [comment]
Hi,

I updated the issue templates to the new version and added the `Laravel version` there.
Thanks!

**Pull request closed without merging**
