### PR TITLE
Address feedback from previous PR

### PR DESCRIPTION
**Pull request by j3j5**
Feedback from #145

### CODE REVIEW

**Comment by nunomaduro** [comment]
Thanks!

**Comment by szepeviktor** [comment]
See : https://travis-ci.org/nunomaduro/larastan/jobs/433160174#L650-L659

**Comment by ondrejmirtes** [comment]
I’m not getting it - how can you call ArrayType without any arguments?

**Comment by nunomaduro** [comment]
@j3j5 @ondrejmirtes My bad. Just made a fix: https://github.com/nunomaduro/larastan/commit/e33a86a867dbdc32c9b52ebea6406e6d5236464a

**Pull request merged**
