### PR TITLE
Fix Call to an undefined method user()

### LINKED ISSUE #44: Call to an undefined method user()
```php
auth()->user()
```

No error on
```php
Auth::user()
```

> Call to an undefined method Illuminate\Contracts\Auth\Factory|Illuminate\Contracts\Auth\Guard::user()

I think the code above is also often used in many different projects.

### PR DESCRIPTION
**Pull request by UksusoFF**
Fixes #44

### CODE REVIEW

**Comment by szepeviktor** [comment]
Very nice.
Thank you.

Please fix this little thing

```diff
diff --git a/src/ReturnTypes/Helpers/AuthExtension.php b/src/ReturnTypes/Helpers/AuthExtension.php
index f8cbcf74f183607b36ce1b131b1fcb74b4c6a1c0..b7294079a13eec842457a63f3e8e2c615bc813ab 100644
--- a/src/ReturnTypes/Helpers/AuthExtension.php
+++ b/src/ReturnTypes/Helpers/AuthExtension.php
@@ -13,12 +13,12 @@ declare(strict_types=1);
 
 namespace NunoMaduro\Larastan\ReturnTypes\Helpers;
 
-use PhpParser\Node\Expr\FuncCall;
+use PHPStan\Type\Type;
 use PHPStan\Analyser\Scope;
+use PHPStan\Type\ObjectType;
+use PhpParser\Node\Expr\FuncCall;
 use PHPStan\Reflection\FunctionReflection;
 use PHPStan\Type\DynamicFunctionReturnTypeExtension;
-use PHPStan\Type\ObjectType;
-use PHPStan\Type\Type;
 
 /**
  * @internal
```

**Comment by nunomaduro** [comment]
Would be cool, if you could add a test on this.

**Comment by UksusoFF** [comment]
As I can see we have trouble with Lumen. How we can fix this if there is no Auth in Lumen?

**Comment by szepeviktor** [comment]
You may help me find a Lumen specialist https://github.com/nunomaduro/larastan/issues/244

**Comment by UksusoFF** [comment]
@nunomaduro @szepeviktor As I see this is old trouble. So maybe can merge without Lumen support?

**Comment by szepeviktor** [comment]
@nunomaduro Is it OK for you?

**Comment by UksusoFF** [comment]
@szepeviktor I dig it deeper and found that we have same troubles as https://github.com/nunomaduro/larastan/issues/71 with auth()->check() and other guard magic calls :(

**Comment by nunomaduro** [comment]
It's fine to just cover partially some of the `auth` calls for now, let's merge it. And add the support to check() and other guard magic calls later.

**Comment by Okipa** [comment]
It seems that this issue is still breaking since this has been released : https://github.com/nunomaduro/larastan/issues/44#issuecomment-524825491

**Pull request merged**
