### PR TITLE
test: add L11 to test matrix

### PR DESCRIPTION
**Pull request by calebdw**
- [x] Added or updated tests
- [x] Documented user facing changes

**Changes**

Hello!

This adds Laravel 11 to the test matrix for phpstan. I suspect there will be some failures to fix.

Thanks!

### CODE REVIEW

**Comment by calebdw** [comment]
Here's the current failures:

```
 ------ ------------------------------------------------------------------------------------------------------------- 
  Line   ApplicationResolver.php                                                                                      
 ------ ------------------------------------------------------------------------------------------------------------- 
  89     Call to static method create() on an unknown class Orchestra\Testbench\Foundation\Application.               
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                          
  91     Call to static method create() on an unknown class Orchestra\Testbench\Foundation\Application.               
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                          
  98     Call to static method applicationBasePath() on an unknown class Orchestra\Testbench\Foundation\Application.  
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                          
  98     Call to static method create() on an unknown class Orchestra\Testbench\Foundation\Application.               
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                          
  100    Call to static method create() on an unknown class Orchestra\Testbench\Foundation\Application.               
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                          
 ------ ------------------------------------------------------------------------------------------------------------- 
```

I'm not sure why PHPStan can't find the class when I can verify that it's installed and in the psr-4 autoload list...

**Comment by szepeviktor** [comment]
```php
require "vendor/autoload.php"; Orchestra\Testbench\Foundation\Application::create();
```
These two run without error.
So it must be PHPStan!

**Comment by szepeviktor** [comment]
PHPStan says 🟢 `[OK] No errors`

for a single file with
```php
<?php

Orchestra\Testbench\Foundation\Application::create();
```

**Comment by calebdw** [comment]
I've already locally tried a lot of things locally that you're trying (great minds think alike haha).

However, this fails inside the `src` dir:

```php
<?php

declare(strict_types=1);

namespace Larastan\Larastan;

use Orchestra\Testbench\Foundation\Application;

final class Test
{
    public function test(): void
    {
        Application::create();
    }
}
```

I suspect that your example wasn't failing phpstan because the file was not inside the `src` directory which is all phpstan reports errors for:

```yaml
parameters:
    level: 8
    phpVersion: 80000
    paths:
        - src
```

**Comment by calebdw** [comment]
It has to be something with the update to Laravel 11 and TestBench 9, but I've checked both repos and haven't really seen any breaking changes or changes to their composer configs.

I can't imagine that it would be PHPStan as it work fine on Laravel 10 and TestBench 8...

**Comment by calebdw** [comment]
Ah, PHPStan is reporting an issue with the following code:

```php
class Application
{
    /**
     * Create new application resolver.
     *
     * @param  string|null  $basePath
     * @param  (callable(\Illuminate\Foundation\Application):(void))|null  $resolvingCallback
     */
    public function __construct(
        protected readonly ?string $basePath = null,
        ?callable $resolvingCallback = null
    ) {
        $this->resolvingCallback = $resolvingCallback;
    }
}
```
> 1. phpstan: Syntax error, unexpected '?', expecting T_VARIABLE on line 77

I think this (the `protected readonly` property promotion) is preventing phpstan from registering the class @ondrejmirtes

**Comment by szepeviktor** [comment]
`phpVersion` is the key.

**Comment by calebdw** [comment]
> phpVersion is the key.

How so? The test matrix calls out 8.2 for L11---shouldn't the version that phpstan uses be the version that's installed in the job?

**Comment by szepeviktor** [comment]
`phpVersion` is for setting PHP version for PHPStan analysis.

**Comment by calebdw** [comment]
PHPStan should use the version of php that's installed in ci (8.2 for L11). All the tests pass when that's commented out so I think the hardcoded value can just be removed altogether

**Comment by szepeviktor** [comment]
Actually all bits of Larastan should be able to run on PHP 8.0 as it supports L9.

https://github.com/larastan/larastan/blob/a02032b140bc33d9eb7b0c4e9095ae8288ec3d53/composer.json#L18

**Comment by calebdw** [comment]
Should be good to go then!

**Comment by calebdw** [comment]
Can this be merged @szepeviktor? My tests are locally failing for L11...

**Comment by szepeviktor** [comment]
I do not know why `phpVersion: 80000` was there.
But I press the merge button for you!

**Comment by calebdw** [comment]
Thank you!!

**Comment by calebdw** [comment]
I'd love it if you could press the "Merge" button for me on the rest of my PRs :stuck_out_tongue_winking_eye: 


You heard from Can? I hope he's doing alright...

**Comment by szepeviktor** [comment]
> You heard from Can?

No.
How is he?

**Comment by calebdw** [comment]
> How is he?

I dunno, it looks like it's been a few weeks since he's been on here (despite a bunch of people pinging him here and on X)---I just hope everything is good

**Pull request merged**
