### PR TITLE
Patch factory

### PR DESCRIPTION
**Pull request by lptn**
- [x] Added or updated tests
- [x] Documented user facing changes
- [x] Updated CHANGELOG.md

**Changes**

Add more type info to Factory class.

**Breaking changes**

- nothing

### CODE REVIEW

**Comment by lptn** [comment]
>See few of the recent tests. Just one file with asserts.

done by [8a849db](https://github.com/nunomaduro/larastan/pull/1219/commits/8a849db410a848ce158db6a1405e38aaeb60a187)

**Comment by canvural** [comment]
Hi,

If it's a copy paste from Laravel, why do we need it here?

**Comment by lptn** [comment]
@canvural 
>If it's a copy paste from Laravel, why do we need it here?

I don't know conventions on this project, guys. Should I just omit doc for such @param?

**Comment by szepeviktor** [comment]
Failing test: https://github.com/nunomaduro/larastan/blob/master/tests/Features/ReturnTypes/ModelFactory.php#L20
The return type is different.

**Comment by canvural** [comment]
@lptn If it has correct docblocks in Laravel, we don't need to add it here at all. Stubs are only for overriding wrong docblocks.

**Comment by szepeviktor** [comment]
> In my case I just needed to override `@return`, but I copy-pasted the whole comment for the method (inc. `@param` and text description). What I supposed to do in this case, just add `@return`?

Please create complete docblocks.

**Comment by lptn** [comment]
@szepeviktor

Actually the type is valid, by PHPStan detect only a parent type. I'm new to PHPStan, I assume the issue is here: https://github.com/nunomaduro/larastan/blob/6a03ad7899f5b71133c459df0260e19491dc5ed4/src/ReturnTypes/ModelFactoryDynamicStaticMethodReturnTypeExtension.php#L55

Can you please help me to fins a solution for this problem? Or at least help me to find a direction to look for.


```json
{
    "message": "Method Tests\\Features\\ReturnTypes\\ModelFactory::testNew() should return Database\\Factories\\PostFactory but returns Illuminate\\Database\\Eloquent\\Factories\\Factory<App\\Post>.",
    "line": 75,
    "ignorable": true
},
```


Thanks!

**Comment by szepeviktor** [comment]
I cannot answer but one of your modifications - maybe `Factory:new` - causes this test to fail.
https://github.com/nunomaduro/larastan/blob/486a0d5f81539a46707456f44ea0d1f281556af1/tests/Features/ReturnTypes/ModelFactory.php#L73-L76

**Pull request closed without merging**
