### PR TITLE
feat: add support for Redis facade

### LINKED ISSUE #14: Redis Facade publish, hmget, expire
```
Call to an undefined static method Illuminate\Support\Facades\Redis::publish().
Call to an undefined static method Illuminate\Support\Facades\Redis::hmget().
Call to an undefined static method Illuminate\Support\Facades\Redis::expire().
```

### LINKED ISSUE #581: laravel redis not able to check
- Larastan Version: 0.5.8
- `--level` used: max

### Description
Is there a trick to step up for  laravel Redis. now I just can only use original redis class could not able to use laravel facades redis. need help.

### Laravel code where the issue was found

```
use Illuminate\Support\Facades\Redis;
$redis  = Redis::connection();
$top_up = $redis->lrange('headquarters_statistics:top_up', 0, -1);
```
`Call to an undefined method Illuminate\\Redis\\Connections\\Connection::lrange().`
```
use Illuminate\Support\Facades\Redis;
$top_up = Redis::lrange('headquarters_statistics:top_up', 0, -1);
```
`Call to an undefined static method Illuminate\\Support\\Facades\\Redis::lrange().
`

------------------------------------------------------------------------------------------------
workaround
```
use Redis;
$redis = new Redis();
$redis->connect('127.0.0.1', 6379);
$top_up = $redis->lrange('headquarters_statistics:top_up', 0, -1);
```

### PR DESCRIPTION
**Pull request by canvural**
Closes #581 
Closes #14 

I'll update the PR once the new PHPStan version is released.

### CODE REVIEW

**Comment by szepeviktor** [comment]
What a simple solution!

**Comment by canvural** [comment]
> What a simple solution!

Indeed. Thanks to the `@mixin` support in PHPStan

I think with this way we will finally have a solution to #203 But it'll be time-consuming to add the annotation to every class.

**Comment by mfn** [comment]
Is there anything the laravel project could do to improve this? For example they _are_ using `@mixin` too in some of their phpdoc (https://github.com/laravel/framework/blob/0b12ef19623c40e22eff91a4b48cb13b3b415b25/src/Illuminate/Queue/Capsule/Manager.php#L11 and others).

**Comment by canvural** [comment]
@mfn `@mixin` should be on the facade class to be able to understand the calls like `Redis::lrange`

Laravel usually has `@see` annotations on their facades. Maybe those can be replaced with `@mixin` instead :thinking: That way both IDE's can autocomplete facade method calls, and static analyzers will be happy.

**Comment by szepeviktor** [comment]
@canvural We are almost out of problems!

**Comment by canvural** [comment]
> @canvural We are almost out of problems!

That's a problem!

**Comment by mfn** [comment]
> Laravel usually has `@see` annotations on their facades.

I kind of read it but didn't realize until I saw a Laravel PR today which added annotations for method and I saw on the boundary the `@see` annotation. Now I got it.

Bold idea: add a temp source hack to see what happens if phpstan/larastan interprets `@see` as mixin for once :)

**Comment by mfn** [comment]
> We are almost out of problems!

I'm sure I can create new ones soon 😝

**Pull request merged**
