### PR TITLE
Fix Str::startsWith args order

### LINKED ISSUE #569: TelescopeServiceProvider.php: Call to an undefined method Illuminate\Contracts\Foundation\Application::isLocal().
- Larastan Version: 0.5.8
- `--level` used: 5
- Laravel framework: 7.10.3
- Telescope version: 3.3.1

### Description

After bumping my composer dependencies,  `phpstan analyse` will throw errors with regards to `app/Providers/TelescopeServiceProvider.php` lines 24 and 42.

```sh
------ -------------------------------------------------------------------------------------
  Line   app/Providers/TelescopeServiceProvider.php
 ------ -------------------------------------------------------------------------------------
  24     Call to an undefined method Illuminate\Contracts\Foundation\Application::isLocal().
  42     Call to an undefined method Illuminate\Contracts\Foundation\Application::isLocal().
 ------ -------------------------------------------------------------------------------------
```

### Laravel code where the issue was found

```php
// inside TelescopeServiceProvider::register()
        Telescope::filter(function (IncomingEntry $entry) {
            if ($this->app->isLocal()) {
                return true;
            }
// ...
```

Line 48 is a same call to `$this->app->isLocal()`.

Clicking through on `isLocal()` in PhpStorm finds the appropriate method, so I am not sure what is going on and why phpstan/larastan is complaining?

### PR DESCRIPTION
**Pull request by szepeviktor**
Closes #569

### CODE REVIEW

**Comment by canvural** [comment]
Thank you! Can you also change it in [here](https://github.com/nunomaduro/larastan/blob/master/src/Properties/Extension.php#L30) and [here](https://github.com/nunomaduro/larastan/blob/master/src/Methods/Pipes/Macros.php#L48) ?

**Comment by szepeviktor** [comment]
Why test didn't catch these?

**Comment by canvural** [comment]
> Why test didn't catch these?

Yeah.. I'll add more tests for this.

**Comment by axit-joost** [comment]
Hi,

First of thanks to both @canvural and @szepeviktor for picking this up so quickly.

I was just wondering: when will a release get tagged that includes this? I am currently locking larastan to 0.5.5 while a release is still pending.

Thanks for your response, and again: thanks for all your work.

**Comment by szepeviktor** [comment]
>  19 days ago

The last release was 2 days **before** this PR :(

We have  32 commits hanging, so very soon!

**Comment by canvural** [comment]
@axit-joost There are couple of bugs I'd like to fix still. But I think we'll release 0.6 this week, or latest beginning of next week :+1:

**Comment by axit-joost** [comment]
Sweet! Looking forward to it.

**Pull request merged**
