### PR TITLE
Fixes replacing type logic in ModelTypeHelper

### PR DESCRIPTION
**Pull request by canvural**
While testing the `master` branch on my work project, I found some return types are not correct.

This PR fixes the issues.

### CODE REVIEW

**Comment by nunomaduro** [comment]
Good job buddy.

**Comment by nunomaduro** [comment]
@canvural can you add a extra line on the changelog?

**Comment by canvural** [comment]
Ah, damn I was just pushing some new code to this branch but you merged :smile: I'll open new PR.

> can you add a extra line on the changelog?

What do you mean exactly? About this change?

**Comment by nunomaduro** [comment]
Yeah - normally a pull request as a meaning. If that meaning is between : `fix|feat` it should be added to the changelog.

That's why I prefer conventional commits: https://www.conventionalcommits.org/en/v1.0.0-beta.4/.

**Comment by szepeviktor** [comment]
> I was just pushing some new code to this branch but you merged 😄 I'll open new PR.

Prepend `WIP:` to the title while you are working on it.

**Pull request merged**
