### PR TITLE
fix: BelongsTo TChildModel generics

### PR DESCRIPTION
**Pull request by calebdw**
- [x] Added or updated tests

This is related to #1870 but does not fully solve it.

**Changes**

This PR fixes the relationship and model relation dynamic return type extensions as well as the relation forwarding extension to properly use `$this` as the BelongsTo TChildModel generic instead of creating a new object class.

This allows inheritance to work properly:

```php
class Baz extends Model
{
    /** @return BelongsTo<Foo, $this> */
    public function foo(): BelongsTo
    {
        return $this->belongsTo(Foo::class);
    }
}

class ChildBaz extends Baz
{
}

// used to be `BelongsTo<Foo, Baz>`!
assertType('BelongsTo<Foo, ChildBaz>', $childBaz->foo());
```

Also fixed type mismatch:

```php
class Baz extends Model
{
    /** @return BelongsTo<Foo, $this> */
    public function foo(): BelongsTo
    {
        // this failed phpstan because the relation method returned
        // `BelongsTo<Foo, Baz>` instead of `BelongsTo<Foo, $this(Baz)>`
        return $this->belongsTo(Foo::class);
    }
}
```

With these two changes, relation forwarding (inside the relation method) started failing with a nesting issue which I fixed while also simplifying the logic:

```php
class Baz extends Model
{
    /** @return BelongsTo<Foo, $this> */
    public function foo(): BelongsTo
    {
        // this was returning `BelongsTo<Foo, BelongsTo<Foo, $this(Baz)>>`
        return $this->belongsTo(Foo::class)->orderBy('id');
    }
}
```

**Breaking changes**

If users have specified the BelongsTo generics with a class or `static` they will need to update to `$this`  (depending on their phpstan level).:
```diff
- /** @return BelongsTo<Foo, Baz> */
- /** @return BelongsTo<Foo, static> */
+ /** @return BelongsTo<Foo, $this> */
```

Thanks!

### CODE REVIEW

**Comment by canvural** [comment]
Hi,

I explained in the issue with more detail. Unfortunately this is not the right fix.

Thanks for understanding!

**Comment by calebdw** [comment]
@canvural, this is a valid issue and is the correct way to handle BelongsTo generics. The BelongsTo relation *does return `$this`*:

https://github.com/laravel/framework/blob/6a8b5051553321a4c18c2eadf17d192c92f3e42e/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php#L212

As I pointed out in the PR description, inheritance is currently broken:

```php
class Baz extends Model
{
    /** @return BelongsTo<Foo, $this> */
    public function foo(): BelongsTo
    {
        return $this->belongsTo(Foo::class);
    }
}

class ChildBaz extends Baz
{
}

// used to be `BelongsTo<Foo, Baz>`!
assertType('BelongsTo<Foo, ChildBaz>', $childBaz->foo());
```

This PR is required for my codebase to reach Level 3

**Comment by canvural** [comment]
It might be a valid issue. But the fix is not right. We cannot force to return `ThisType`

**Comment by calebdw** [comment]
Why not? `ThisType` is exactly what should be returned---the BelongsTo returns the `$this` that the relation was called on

**Comment by canvural** [comment]
BelongsTo does not return `$this`. It returns the child object.

**Comment by calebdw** [comment]
For this class:

```php
class Baz extends Model
{
    /** @return BelongsTo<Foo, $this> */
    public function foo(): BelongsTo
    {
        return $this->belongsTo(Foo::class);
    }
}
```

Calling a method **does return $baz**--- the instance that the relationship was defined on, not a new a new Baz or static instance.
```php
$baz = Baz::first();
// this returns $baz 
$baz->foo()->associate($foo)
```

In this case `$this` when defined on a model is the most correct type

**Comment by canvural** [comment]
> the instance that the relationship was defined on, not a new a new Baz 

In the eyes of static analysis there is no difference there. 

I agree there might be an issue with the inheritance. But returning `ThisType` is not correct fix. We need to find other ways.

**Pull request closed without merging**
