### PR TITLE
Forward calls on Model when subclass is not known

### PR DESCRIPTION
**Pull request by spawnia**
- [x] Added or updated tests
- [x] Documented user facing changes
- [x] Updated CHANGELOG.md

**Changes**

Avoid false-positive when calling static builder methods such as `::find()` on Model classes where the concrete subclass is not yet known.

**Breaking changes**

No, allows more valid programs.

### CODE REVIEW

**Comment by canvural** [comment]
I think it's failing because the type hint is `Model` If you give a specific model like `User` or `Account` it should work.

What is the use case for this?

**Comment by spawnia** [comment]
> I think it's failing because the type hint is `Model` If you give a specific model like `User` or `Account` it should work.

Right, i saw that in the test case above. It should also work with the generic `Model` type, though.

> What is the use case for this?

I hit this in Lighthouse, where we interact with user-defined models in a generic way. See https://github.com/nuwave/lighthouse/blob/f32243e71930e515a4b8661520c67d4f1ba04416/src/Schema/Directives/DeleteDirective.php#L60

**Comment by canvural** [comment]
[This](https://github.com/nunomaduro/larastan/blob/master/src/Methods/ModelForwardsCallsExtension.php) extension is responsible for finding the missing methods on models. But [this](https://github.com/nunomaduro/larastan/blob/master/src/Methods/ModelForwardsCallsExtension.php#L33-L35) check prevents it running for `Model` (Model is not subclass of Model)

So you can try to change that check to `if ($classReflection->getName !== Model::class && ! $classReflection->isSubclassOf(Model::class))` and then you can see what is the output and try to improve on that.

**Comment by canvural** [comment]
Seems like it works with my suggested change. But you have to remove the `@mixin` [here.](https://github.com/nunomaduro/larastan/blob/master/tests/Application/app/User.php#L19) I added that to simulate some cases where users would run `laravel-ide-helper` and it adds this mixin. You can see the discussion at #555 

So, I guess `@mixin \Eloquent` needs to be ignored somehow.

**Comment by spawnia** [comment]
@canvural your proposed fix does indeed, work - thank you!

I found that this does allow some invalid programs:

```
\Illuminate\Database\Eloquent\Model::find(1);

/** @var class-string<\Illuminate\Database\Eloquent\Model> */
$model = 'Illuminate\Database\Eloquent\Model';
$model::find(1);
```

I dug around PHPStan's `ClassReflection` to check if the source of the class can be known. For example, here it can be known for sure that the passed in `Model` is an instance and calling `::find()` works:

```
    public function testFindOnGenericModel(Model $model): ?Model
    {
        return $model::find(1);
    }
```

The following example is ambigious:

```
    /**
     * @param  class-string<Model>  $modelClass
     */
    public function testFindOnModelClassString(string $modelClass): ?Model
    {
        return $modelClass::find(1);
    }
```

Is there a way to specify a class-string must be a subclass of the given type?

**Comment by spawnia** [comment]
I guess my branch was not up to date, the mixin does seem to be causing problems.

**Comment by spawnia** [comment]
@canvural opened an issue with PHPStan that might help to solve this use case. https://github.com/phpstan/phpstan/issues/3256

Pragmatically, i think it should be extremely rare that developers actually try to call something like `Model::find()`. If they do, the error is very immediate and clear:

```
PHP Error:  Cannot instantiate abstract class Illuminate/Database/Eloquent/Model in /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1634
```

**Comment by canvural** [comment]
Hi,

PHPStan 0.12.24 is released. So I updated master branch, and [added](https://github.com/nunomaduro/larastan/commit/300ec5ac7c2227e47eea4e403a8cd8f44d180360) `Eloquent` to `mixinExcludeClasses` config option.

So if you rebase this branch on master the tests should pass. And if you can update the changelog we can merge this :+1:

**Comment by spawnia** [comment]
Nicely done @canvural. It's unfortunate the types generated by `laravel-ide-helper` are so inaccurate.

**Comment by mfn** [comment]
> It's unfortunate the types generated by `laravel-ide-helper`

We can improve it, what needs to be done ? 😄

**Comment by spawnia** [comment]
@mfn just to be clear, i was not bashing `laravel-ide-helper`. I think it does its part quite well actually - provide useful type hints that play nicely with IDE's.

Many of the nuances of Laravel's magic can't really be expressed correctly through a nominal type system. Other parts can be expressed only through non-standard, PHPStan-specific annotations, for which proper IDE support does not exist.

**Pull request merged**
