### PR TITLE
fix: incorrect return type by `route` on Request class

### LINKED ISSUE #1112: `route()` on Request not recognized
- Larastan Version: 1.0.3
- `--level` used: 6
- Pull request with failing test: /

### Description

I was wondering how do you handle that case the best. I know, you could always check with `instanceof` (https://phpstan.org/writing-php-code/narrowing-types), but it blows the could heavily up. Have you any tips?

Unbenannt

### PR DESCRIPTION
**Pull request by fragkp**
- [x] Added or updated tests
- [x] Documented user facing changes
- [x] Updated CHANGELOG.md

Resolves #1112 

**Changes**

Returns now the correct return type by given parameters.

**Breaking changes**

No breaking changes.

**Note**

First time using the extension mechanism. Please review carefully, thx ❤️

### CODE REVIEW

**Review by canvural — CHANGES_REQUESTED** [review]
Hi,

Thank you!

Overall it looks fine. But couple of things:
- Please target the `master` branch. `1.x` branch will no longer receive new features. Only critical bug fixes.
- Changelog does not look correct. But I guess when you target the `master` branch, you can just add your changes.

**Comment by fragkp** [comment]
@canvural Rebase to `master` is done.

**Review by canvural — APPROVED** [review]

**Comment by canvural** [comment]
Thank you!

**Comment by szepeviktor** [comment]
@fragkp Very well done.

**Pull request merged**
