### PR TITLE
Update phpstan-dev.yml

### PR DESCRIPTION
**Pull request by szepeviktor**
# testing...

### CODE REVIEW

**Comment by szepeviktor** [comment]
@canvural 🌟 

> Installing phpstan/phpstan (1.7.x-dev 5410365): Extracting archive

**Comment by canvural** [comment]
Huh, it's weird it works. When I tested like this it installed `dev` version of every package.

What is the advantage of changing the order though?

**Comment by szepeviktor** [comment]
> What is the advantage of changing the order though?

- configure 👉🏻 does nothing
- upgrade to phpstan/phpstan:@dev 👉🏻 does nothing
- do the actual installation 👉🏻 installs packages

**Comment by canvural** [comment]
Makes sense. Thank you!

**Pull request merged**
