### PR TITLE
Update changelog and upgrade guide

### PR DESCRIPTION
**Pull request by canvural**

### CODE REVIEW

**Comment by canvural** [comment]
No, I don't have unfortunately.

**Comment by nunomaduro** [comment]
Alright, I write a blogpost about this. I will make sure to include your name on the tweet and blogpost very first line. This release is HUGE!

**Comment by canvural** [comment]
Sure. Feel free to ask anything specific about the changes.

**Comment by canvural** [comment]
Should we do a release now or do you want to do the release with the blog post?

**Comment by canvural** [comment]
I drafted a new release, with the description of what changed. So we can make the release any time you want.

**Comment by nunomaduro** [comment]
You can release it now, I will do the blogpost tonight and publish it tomorrow morning.

**Comment by mfn** [comment]
I appreciate the proper changelog on the tags / releases on github;  they're much easier to find  and skim for relevant things (same as changelog.md), just wanted to mention (=appreciate) it.

Btw I saw the changelog was not updated with individual feature PRs but it was a once-done effort right before the release. Just wondering if there's a reason for this and why PRs shouldn't this include directly. Properly only a "me" problem, but seems less work to hunt down the PR after the fact for a release :)

**Comment by canvural** [comment]
That's mostly the result of me being lazy :sweat_smile: And forgetting to add it to changelog. But I agree it'd be easier to do a release if we keep track of the changes alongside of the code changes. I'll try to do it for the next release.

**Comment by nunomaduro** [comment]
Maybe @mfn can help us out doing that. 👍

**Comment by mfn** [comment]
> That's mostly the result of me being lazy 😅

Well, nothing to argue here.

> Maybe @mfn can help us out doing that. 👍

hah! 😄 

- I would make a PR template to include a checkbox: "- [ ] did you add a changelog entry?"
  Maybe upfront discussion/docs to make it clear what needs a changelog and whatnot
- require/remind people to add it when reviewing 🤷‍♀️

**Comment by nunomaduro** [comment]
Fell free to do a pull request adding those things.

**Pull request merged**
