### PR TITLE
feat: run integration tests in Github Actions

### PR DESCRIPTION
**Pull request by canvural**
This PR adds a new GA that will clone some popular open source Laravel projects that uses Larastan, and run the Larastan on it.

This way we'll see if our changes will break any stuff in real world applications.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Maybe `composer config minimum-stability dev` will do.

**Comment by szepeviktor** [comment]
I think `if:` must be written in all steps, not on job level.

**Comment by canvural** [comment]
> I think `if:` must be written in all steps, not on job level.

Nah, I think it was because there were also `pull_request` and `push`. `workflow_run` should be the only one. We will see.

**Comment by szepeviktor** [comment]
We may need clean up that directory as the first command `rm -rf ../e2e/integration/repo`

**Comment by canvural** [comment]
> We may need to clean up that directory as the first command `rm -rf ../e2e/integration/repo`

I don't think so. These are defined in the matrix so they are ran separately.

**Comment by canvural** [comment]
Hmm, the `integration-tests` didn't even run last time.

I found this in the [docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run)

> Note: This event will only trigger a workflow run if the workflow file is on the default branch.

Maybe we need to merge this now 🤔

**Comment by szepeviktor** [comment]
I would open a temporary repo with `echo 1;` and `echo 2;` as commands.

**Comment by canvural** [comment]
So this is is waiting for https://github.com/monicahq/monica/pull/6305 After that I'll replace the commit hash and we can try again.

**Pull request merged**
