### PR TITLE
Fix for issue #1487

### PR DESCRIPTION
**Pull request by rcerljenko**
Fixes https://github.com/nunomaduro/larastan/issues/1487

### CODE REVIEW

**Comment by canvural** [comment]
Thank you!

**Comment by rcerljenko** [comment]
np.. since we're here could you somehow exclude a folder from that rule? eg: I want to check my views but i dont want to check `resources/views/vendor` views because mostly i don't use them but they get published witrh everything else...

**Comment by canvural** [comment]
`views/vendor` should be skipped already. Thanks to this [line.](https://github.com/nunomaduro/larastan/blob/master/src/Support/ViewFileHelper.php#L64) Does it not work for you?

**Comment by rcerljenko** [comment]
again... directory separator haha  :) i'll provide another PR for that

**Comment by rcerljenko** [comment]
here it is => https://github.com/nunomaduro/larastan/pull/1489

**Pull request merged**
