### PR TITLE
fix: PHPStan 0.12.82 compatibility

### LINKED ISSUE #796: PHPStan 0.12.82 compatibility
In [PHPStan v0.12.82](https://github.com/phpstan/phpstan/releases/tag/0.12.82) release there were changes related to how `static` keyword is resolved. This caused some issues in Larastan. Need to investigate and fix.

### PR DESCRIPTION
**Pull request by canvural**
- [x] Added or updated tests
- [ ] Documented user facing changes
- [x] Updated CHANGELOG.md

Resolves #796 

**Changes**

- Introduced local cache to some extensions
- If the generic model is the Eloquent model, some extensions are skipping some checks.

**Breaking changes**

none

### CODE REVIEW

**Comment by olivernybroe** [comment]
I just tested it on our codebase, and no crashes on a complete run for us :)

**Comment by canvural** [comment]
@olivernybroe Thank you!

I also tested on some open source projects + my own. Everything seems fine :+1:

**Comment by szepeviktor** [comment]
@canvural Very well done!

**Comment by bytestream** [comment]
It looks like there might be some memory leaks in this
```
Reached internal errors count limit of 50, exiting...                      
     Internal error: Child process timed out after 300.0 seconds. Try making it longer with parallel.processTimeout setting.                            
     Child process error (exit code 255):                                       
     In NodeScopeResolver.php line 574:                                         
                                                                                
       Out of memory (allocated 9297731584) (tried to allocate 8589934600 bytes)                                                                     
                                                                                
     mmap() failed: [12] Cannot allocate memory                                 
                                                                                
     mmap() failed: [12] Cannot allocate memory                                 
     Fatal error: Out of memory (allocated 9297731584) (tried to allocate 8589934600 bytes) in                                                       
     phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php on line 574  
```

**Comment by szepeviktor** [comment]
# 😲 

Should we make it an Issue?

**Pull request merged**
