### PR TITLE
fix: support extended schema classes in schema aggregator

### PR DESCRIPTION
**Pull request by tpetry**
- [ ] Added or updated tests
- [ ] Documented user facing changes
- [ ] Updated CHANGELOG.md

**Changes**

The `SchemaAggregator` inspects all migrations to learn which Eloquent attributes do exist. But the schema and blueprint classes had been hardcoded so any class extending them was not supported. There are some packages extending the Laravel's migration classes and the second they are used larastan was not able to infer the model attributes anymore (e.g. tpetry/laravel-postgresql-enhanced#43). I've changed the implementation slightly to check whether the `Schema` and `Blueprint` class are the original Laravel classes or any class extending them.

### CODE REVIEW

**Comment by canvural** [comment]
I fixed it like this and added a test: 3eb62a4

Thank you!

**Comment by tpetry** [comment]
That looks a lot cleaner than my solution!

**Comment by tpetry** [comment]
@canvural The fix is not complete. The `Blueprint` class also needs to have that more generic handling:  [SchemaAggregator.php#L128](https://github.com/nunomaduro/larastan/blob/3eb62a4398130b2684fc78f590b30ef9690c0315/src/Properties/SchemaAggregator.php#L128)

**Comment by canvural** [comment]
Ah I missed that. I'll add later. Thanks.

**Pull request closed without merging**
