### PR TITLE
Add translation return type extensions.

### PR DESCRIPTION
**Pull request by mad-briller**
- [x] Added or updated tests
- [ ] Documented user facing changes

**Changes**
Adds a few return type extensions for translation related features to provide more contextual typing, meaning less false positives

### CODE REVIEW

**Comment by mad-briller** [comment]
monicahq/chandler failure seems to be related to the improved console command analysis released recently, not a result of this change

**Comment by szepeviktor** [comment]
I like your TranslationHelper usage 💝 much netter than we write here.

**Comment by mad-briller** [comment]
I think that's fine, it will solve the false positives which is my major concern with this change 

I appreciate the desire to avoid dynamic analysis as it adds complexity

I'll try to revise this soon

**Comment by mad-briller** [comment]
can a benevolent union be specified in a phpdoc? i don't think it can?

**Review by canvural — APPROVED** [review]

**Comment by canvural** [comment]
> can a benevolent union be specified in a phpdoc? i don't think it can?

It's kinda possible, but it's highly internal stuff used in PHPstan. So extension is the right way to go 👍🏽 

Thank you!

**Pull request merged**
