### PR TITLE
feat: support sole method

### PR DESCRIPTION
**Pull request by ThibaudDauce**
- [x] Added or updated tests
- [ ] Documented user facing changes
- [x] Updated CHANGELOG.md

**Changes**

Add support for the `sole` method on Laravel 8.

(sorry I did something wrong and it auto-close the previous PR… Don't really know why…)

### CODE REVIEW

**Review by szepeviktor — APPROVED** [review]

**Comment by ThibaudDauce** [comment]
@canvural As I was expected the sole presence of the docblock on the other versions is failing the tests.

**Comment by canvural** [comment]
Ah, you are right. I totally forgot about that. I'm sorry!

Ok then let's remove it and hope PHPStan merges definitions from stubs and actual method reflections :smile:

**Comment by szepeviktor** [comment]
> hope PHPStan merges definitions from stubs and actual method reflections

Stubs are there specifically to **overwrite** actually PHPDoc blocks in the source code.

**Comment by canvural** [comment]
Thank you!

**Pull request merged**
