### PR TITLE
Import classes and get rid of temp vars

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by nunomaduro** [comment]
@szepeviktor This seems coding style related. Can we leave this pull request on hold? I am will pull request my cs config to pest repository tonight and you can copy from it?

**Comment by szepeviktor** [comment]
Okay.

**Comment by nunomaduro** [comment]
@szepeviktor Thank you, you are the best!

**Comment by szepeviktor** [comment]
@nunomaduro Could you lend me 1 click?

**Comment by nunomaduro** [comment]
Hey @szepeviktor, this a coding style pull request. This kind of stuff shouldn't be done by humans, but by tools.

Fell free to open a pull request adding php-cs-fixer.

Here is how to proceed:

1. Open a new pull request
2. Create this file: https://github.com/pestphp/pest/blob/master/.php_cs. ( and adapt it )
3. Add this dependency: https://github.com/pestphp/pest/blob/283d8f3e03956cbee210d69edd5ad13690078723/composer.json#L47.
4. Add those composer scripts `lint` & `test:lint`: https://github.com/pestphp/pest/blob/283d8f3e03956cbee210d69edd5ad13690078723/composer.json#L68.
5. Run `composer lint` locally
6. Finally add `composer test:lint` to the CI scripts.

Thanks buddy!

**Comment by szepeviktor** [comment]
AFAIK PhpCsFixer cannot convert FQCN-s to short ones.

only:

```
fully_qualified_strict_types [@PhpCsFixer]

Transforms imported FQCN parameters and return types in function arguments to short version.
```

**Comment by nunomaduro** [comment]
@szepeviktor Let's first have a coding style tool, and than talk about that. 👍

**Comment by szepeviktor** [comment]
Slevomat's `ReferenceUsedNamesOnly` is the 💯 choice but it cannot autofix problems.

**Pull request closed without merging**
