### PR TITLE
Document concrete steps needed for contributing

### PR DESCRIPTION
**Pull request by spawnia**
I found myself a bit lost and had to dig around the project to see how to run the tests, this change should make this process a bit easier for newcomers.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Do we really need contributors who need instructions like `Clone your fork`?

**Comment by nunomaduro** [comment]
I am ok on having instructions like `Clone your fork`. You would be suprised to see how many people don't know those things.

**Comment by spawnia** [comment]
I just noticed you do not have a PR template yet. I took the liberty to move parts of the guidelines that relate to completeness of the PR there.

This kind of templating has worked great for me in https://github.com/nuwave/lighthouse, the amount and quality of contributions has been quite good.

**Comment by canvural** [comment]
Thank you!

**Pull request merged**
