### PR TITLE
Test ourselves with PHPStan

### PR DESCRIPTION
**Pull request by szepeviktor**
@nunomaduro This is very interesting.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
My two PRs also address this (fix errors):

#65, #66.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by nunomaduro** [comment]
@szepeviktor Thanks! Just merged and upgraded the `--level` to `max`.

**Comment by szepeviktor** [comment]
@nunomaduro Thanks.
Please remove the change from tests/laravel-test.sh as it does exactly the same for the second time.

**Pull request merged**
