### PR TITLE
Run CI nightly

### PR DESCRIPTION
**Pull request by szepeviktor**
We already run nightly.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Success 🍏 

> Upgrading phpstan/phpstan (1.7.12 => 1.7.x-dev a48f5e2)

**Comment by szepeviktor** [comment]
`phpstan/phpstan:1.7.x-dev`

The branch name changes with every major release!
https://github.com/phpstan/phpstan/issues/7487

**Comment by canvural** [comment]
Hi,

I'd rather have a new `job`, that just clones the repo, runs `composer require --no-update phpstan/phpstan:@dev` and then runs `composer test:types`

> The branch name changes with every major release!

I think `phpstan/phpstan:@dev` can solve that.

**Comment by szepeviktor** [comment]
> I'd rather have a new `job`

This CI job does all steps we have.
Is it too complete :) for you?

**Comment by canvural** [comment]
But this would run the scheduled job at midnight **only** with `@dev` version of PHPStan. Wouldn't it? I just want another job that runs at ever midnight with `@dev` version on top of regular runs.

**Comment by szepeviktor** [comment]
Your wish is my command.

**Comment by szepeviktor** [comment]
@canvural There is something: https://github.com/nunomaduro/larastan/actions/runs/3186357016/jobs/5196858847

**Pull request merged**
