### PR TITLE
Fix compatibility with PHPStan 0.11.8

### PR DESCRIPTION
**Pull request by ondrejmirtes**

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thank you.

**Comment by ondrejmirtes** [comment]
Can you please tag a new version? :)

**Comment by szepeviktor** [comment]
I think @nunomaduro will.

**Comment by szepeviktor** [comment]
And maybe raise required version of PHPStan.

**Comment by ondrejmirtes** [comment]
Oh shoot, that's right. Opened https://github.com/nunomaduro/larastan/pull/270 for that.

**Pull request merged**
