### PR TITLE
fix: also ignore errors folder

### PR DESCRIPTION
**Pull request by szepeviktor**
- [ ] Added or updated tests
- [ ] Documented user facing changes
- [ ] Updated CHANGELOG.md

props @rcerljenko 
Was #1496

### CODE REVIEW

**Comment by szepeviktor** [comment]
@rcerljenko There were multiple problems.

1. that PR came from your master branch
2. new commits from our master were not rebased but merged

**Comment by rcerljenko** [comment]
@szepeviktor good to know... i'll use a different branch next time and not master... thanks!

**Comment by rcerljenko** [comment]
hi @szepeviktor could you merge and release this if it's ready?  :)

**Comment by szepeviktor** [comment]
Here you go https://github.com/nunomaduro/larastan/releases/tag/2.3.4

**Comment by rcerljenko** [comment]
thanks man!

**Pull request merged**
