### PR TITLE
Updated stubs

### PR DESCRIPTION
**Pull request by ricklambrechts**
- [ ] Added or updated tests
- [ ] Documented user facing changes
- [ ] Updated CHANGELOG.md

**Changes**

Added psalm types because psalm does not understand 'model-property'.

**Breaking changes**

### CODE REVIEW

**Comment by szepeviktor** [comment]
Hello-hello @ricklambrechts! 👋🏻 

We are a PHPStan extension :)

**Comment by szepeviktor** [comment]
Does https://github.com/psalm/psalm-plugin-laravel work for you?

**Comment by szepeviktor** [comment]
> There are 3 options to fix that:

Could you add a 4th option:

- copy Larastan stubs to https://github.com/psalm/psalm-plugin-laravel/tree/master/stubs

**Comment by canvural** [comment]
Hi,

You are correct `model-property` type is special to Larastan. So we might need to prefix it.

But I am not sure if overwriting `@param` tags is really supported by PHPStan or not. A simple example show that `@phpstan-param` takes precedence: https://phpstan.org/r/c5bdc938-9a8f-42d2-af2d-aec16237b918So I hope it can work on all cases.

So what I would like to see is to use `@phpstan-param` whereever `model-property` is used. And have `@param` for normal PHPDocs.

Can you update the PR according to that? Thanks.

**Comment by canvural** [comment]
Closing this as it is out of scope currently. Psalm plugin can write it's own stubs for generics.

**Pull request closed without merging**
