### PR TITLE
Updates changelog

### PR DESCRIPTION
**Pull request by mvdnbrk**

### CODE REVIEW

**Comment by nunomaduro** [comment]
Commit just desapear, wtf.

**Comment by nunomaduro** [comment]
Thanks!

**Comment by szepeviktor** [comment]
@nunomaduro a responsible :) maintainer would always send code through a PR
please consider that

**Comment by nunomaduro** [comment]
@szepeviktor Hum? This is docs here.

**Comment by nunomaduro** [comment]
In this context, for everything that's not code, it's fine to commit directly.

**Pull request merged**
