### PR TITLE
deps: require PHPStan v0.12.70

### PR DESCRIPTION
**Pull request by chrisp-github**
This solves the OutOfBoundsException: Package "project/project" is not installed error

- [ ] Added or updated tests
- [ ] Documented user facing changes
- [x] Updated CHANGELOG.md

getsentry/sentry-symfony#383

**Changes**

Updated php phpstan/phpstan from v0.12.65 -> v0.12.70
See [phpstan/releases/tag/0.12.70](https://github.com/phpstan/phpstan/releases/tag/0.12.70)

**Breaking changes**

None

### CODE REVIEW

**Comment by szepeviktor** [comment]
Isn't instead related to the latest Composer v2 release?
Could you try with 2.0.8 and 2.0.9?

**Comment by szepeviktor** [comment]
@chrisp-github Please force-push with an email address registered here on GitHub.
Thanks.

**Comment by chrisp-github** [comment]
@szepeviktor I have pushed again with the right email, sorry about that.

The fix here is that they rebuilt the .phar that they use with composer v2.

**Comment by szepeviktor** [comment]
Please merge master to get #775

**Comment by chrisp-github** [comment]
@szepeviktor Sorted.

**Review by szepeviktor — APPROVED** [review]

**Comment by canvural** [comment]
Thank you!

**Comment by HSPDev** [comment]
**IF THIS STILL DOESN'T WORK!**

```composer self-update```

I had a version `2.0.6` or something, latest version `2.0.11` fixed everything (together with `rm -rf vendor/` and `composer install` just to be safe, I had tried those before, but don't know if they are needed after updating).

**Comment by szepeviktor** [comment]
> latest version `2.0.11` fixed everything

There was a lot of turbulence from v2.0.0 to v2.0.11.
https://github.com/composer/composer/releases

**Pull request merged**
