### PR TITLE
Fix CS

### PR DESCRIPTION
**Pull request by szepeviktor**
We have 100 `function foo();`
and 27 `function bar() {}`

What to do now?

### CODE REVIEW

**Comment by canvural** [comment]
I think every stub should use `;`

So can you update this PR to fix everything?

**Comment by szepeviktor** [comment]
Oh no! Only interfaces may have `function foo();`

**Comment by canvural** [comment]
Not only interfaces but also methods. So only functions should have `{}`

**Comment by szepeviktor** [comment]
> Not only interfaces but also methods.

I've tried in a commit above. Everything went berserk :x:

**Comment by canvural** [comment]
Thank you!

**Pull request merged**
