### PR TITLE
Illuminate\Database\Query\Builder::get() stub

### PR DESCRIPTION
**Pull request by rudiedirkx**
- [ ] Added or updated tests
- <s>Documented user facing changes</s> none

**Changes**

Adds stub function for `Illuminate\Database\Query\Builder::get()` to make the return type better: 'Collection of objects' instead of just 'Collection (of mixed)'.

**Breaking changes**

No breaking changes.

----

Tests?

### CODE REVIEW

**Comment by calebdw** [comment]
This kind of fix should really be PR'd to the framework first to fix it at the source

**Comment by rudiedirkx** [comment]
Does Laravel accept `list<string>` specificity (instead of just `array`)? Is that general phpdoc enough? Or psalm-like enough?

(Wow, that's a lot of tests! 😆)

**Comment by calebdw** [comment]
Should be fine, but you could also just use `array<int, string>`

**Comment by canvural** [comment]
Hi,

This looks good but it needs to have tests. You can add it in `query-builder.php` Also the stub needs to be added to other versions.

**Comment by rudiedirkx** [comment]
In Laravel soon 😮 https://github.com/laravel/framework/pull/53567 Good advice @calebdw

**Comment by canvural** [comment]
For this kind of changes we can use stub files. That way we can have the changes faster and also in other Laravel versions too (where it makes sense) I added it to the stubs. Thank you for the PR for the Laravel.

**Pull request closed without merging**
