### PR TITLE
Migrates to GitHub Actions

### PR DESCRIPTION
**Pull request by nunomaduro**
This pull request replaces Travis by Github Actions.

@szepeviktor Do you mind of adding the remaining verifications we had on travis? Like testing a base Laravel app, etc.

### CODE REVIEW

**Comment by szepeviktor** [comment]
> Do you mind of adding the remaining verifications we had on travis? Like testing a base Laravel app, etc.

@nunomaduro Nice little tragedy that you have put together here.

May I rethink CI for GitHub Actions?

**Comment by nunomaduro** [comment]
@szepeviktor What do you mean? Can you elaborate?

**Comment by szepeviktor** [comment]
> @szepeviktor What do you mean? Can you elaborate?

- all steps run in one job: so you don't know what went wrong
- stability is undefined
- `laravel` is unused

**Comment by nunomaduro** [comment]
We are using GitHub actions in all projects on the Laravel organization, and we didn't found any of the problems you are mentioning.

**Comment by szepeviktor** [comment]
All right, I keep my 🐌-pace, Laravel may 🏃 as fast as you want.

May I rethink CI for GitHub Actions?

**Comment by szepeviktor** [comment]
I would aim for something like https://github.com/ergebnis/php-library-template

**Comment by canvural** [comment]
@szepeviktor Go for it :+1:

**Comment by canvural** [comment]
Hi @szepeviktor will you continue this PR? If not I can do it.

**Comment by szepeviktor** [comment]
Yes, in a few days.

**Comment by nunomaduro** [comment]
Done. We now have a CI that runs in 2 minutes instead of 3 hours. Fell free to propose changes via pull request.

**Pull request merged**
