### PR TITLE
Add support for the trans() helper return types

### PR DESCRIPTION
**Pull request by Korri**
This adds support for the return type of `trans()` vs `trans('key')`.

I also added test for the other helper return type extensions

### CODE REVIEW

**Comment by Korri** [comment]
Not sure why this if failing, let me know if I can fix it on my side.

**Comment by szepeviktor** [comment]
all new files seems to be 0644

**Comment by nunomaduro** [comment]
@szepeviktor Hey buddy, you are taking care of this right?

**Comment by szepeviktor** [comment]
@nunomaduro Yes.

**Comment by szepeviktor** [comment]
Solved in https://github.com/nunomaduro/larastan/commit/e1e8d6e51e20ff4b634871e7f30d7d460ae02a88

@nunomaduro Is this PR ready to merge?

**Comment by nunomaduro** [comment]
Seems that tests are not passing ?

**Comment by szepeviktor** [comment]
I've committed the fix to master so testing is only possible if you update this PR.

**Comment by nunomaduro** [comment]
I will rebase it.

**Comment by nunomaduro** [comment]
Perfect Pull Request, Thanks @Korri !

**Pull request merged**
