### PR TITLE
Probable fix for #559

### LINKED ISSUE #559: Bug with autoloading on phpstan 0.12.22
- Larastan Version: 0.5.7
- PhpStan Version: 0.12.22
- `--level` used: max

### Description
For latest version of phpstan (0.12.22)!

On analyze action:
```php
 ErrorException thrown in /builds/trv3/core/vendor/nunomaduro/larastan/src/ApplicationResolver.php on line 109 while loading bootstrap file /builds/trv3/core/vendor/phpstan/phpstan/../../nunomaduro/larastan/bootstrap.php: Undefined index: AI\Core\
```

Method ApplicationResolver@getProjectSearchDirs has wrong composer dir:

Expected: `/home/vagrant/projects/core/vendor/composer`
Actual: `phar:///home/vagrant/projects/ai/core/vendor/phpstan/phpstan/phpstan/vendor/composer`

phpstan code reference: https://github.com/phpstan/phpstan-src/commit/a1d3990c95b7a064a0451111153a6bef39f5d9a2

### PR DESCRIPTION
**Pull request by ondrejmirtes**
Fixes #559

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
So the failing test is there because PHPStan defines global `resolve` function - because it includes an unprefixed Hoa library. I'll see if I can do without that today.

But this PR definitely fixes the issue with the autoloader.

**Comment by ondrejmirtes** [comment]
Just pushed a commit that requires current dev-master of PHPStan - and it works :) This is what fixes it: https://github.com/phpstan/phpstan-src/commit/70e559bec1878885efb433e07d0d1425b5128091 (diff of a diff - how meta!)

So we should merge this - once we do, I'll release PHPStan 0.12.23 and you should release v0.5.8.

**Comment by nunomaduro** [comment]
Testing things out locally now..

**Comment by ondrejmirtes** [comment]
Let me know somewhere when you're ready to release it, I'll tag PHPStan 0.12.23 before you :)

**Comment by szepeviktor** [comment]
Thank you.

**Comment by nunomaduro** [comment]
Tested locally in Laravel and Laravel packages. Tests are passing locally and on the CI.

Everything sounds good to me. @ondrejmirtes Please release the new version, and I will follow you on that.

**Comment by ondrejmirtes** [comment]
Released: https://github.com/phpstan/phpstan/releases/tag/0.12.23

**Pull request merged**
