### PR TITLE
Handle redirect() and view() helper function

### LINKED ISSUE #68: Call to an undefined method route()/back().
```
return redirect()->route('index');
```
Produce:
> Call to an undefined method Illuminate\Http\RedirectResponse|Illuminate\Routing\Redirector::route()
--------
```
return redirect()->back();
```
Produce:
> Call to an undefined method Illuminate\Http\RedirectResponse|Illuminate\Routing\Redirector::back().

### PR DESCRIPTION
**Pull request by Korri**
Fixes #68

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thank you, it seems to be correct.

**Comment by nunomaduro** [comment]
Thanks @Korri for this! The version `v0.3.2` has been tagged.

**Comment by barryvdh** [comment]
I still get this:

```
38     Method App\Http\Controllers\SomeController::index() should return
         Illuminate\Http\Response but returns Illuminate\View\View.    

6     Method App\Http\Controllers\HomeController::index() should return      
         Illuminate\Http\Response but returns Illuminate\Http\RedirectResponse.
```

Am I missing something? I'm on 0.3.12 with default config.

**Comment by nunomaduro** [comment]
@barryvdh Can you create a new issue with your exact code of the methods `HomeController::index()` and `SomeController::index()`?

**Comment by barryvdh** [comment]
Oh sorry, I see it already, the default typehint is wrong for the make:auth stub. https://github.com/laravel/framework/blob/af510b80fdf16ea1b6de908d9fdcc98687b9b4bd/src/Illuminate/Auth/Console/stubs/make/controllers/HomeController.stub
Created an issue there: https://github.com/laravel/framework/pull/26830

**Pull request merged**
