### PR TITLE
Allow dynamic model properties with underscores

### LINKED ISSUE #1790: Internal error: Dynamic model properties with underscores cannot be used
- Larastan Version: 2.6.5
- `--level` used: 0
- Pull request with failing test: https://github.com/larastan/larastan/pull/1792

### Description

After updating to 2.6.5, the analysis fails with an internal error:

Internal error: Internal error: Method __test() was not found in reflection of class App\Models\Model. while analysing file /app/Test.php  

### Laravel code where the issue was found

```php

$foo = new App\Models\Model;

$foo->__test = 'bar';

```

### PR DESCRIPTION
**Pull request by Brenneisen**
- [x] Added or updated tests
- [x] Documented user facing changes

Fixes https://github.com/larastan/larastan/issues/1790.

**Changes**

Fixes an internal error and allows dynamic model properties with underlines.

**Breaking changes**

None

### CODE REVIEW

**Comment by Brenneisen** [comment]
@canvural @nunomaduro @szepeviktor Do you have the chance to have a look at it? Our tests are currently failing due to the problem. Thank you very much!

**Review by szepeviktor — APPROVED** [review]

**Comment by KiroVasilovski** [comment]
Hello,
I've been having the same issue as described in the ticket [#1790](https://github.com/larastan/larastan/issues/1790). This solution works for me.

**Comment by Scheissy** [comment]
Hey there,
it would help me a lot if you could merge this. Thanks!

**Comment by Brenneisen** [comment]
@szepeviktor Is there anything blocking this or could you merge it? Unfortunately, we need the fix for our build pipeline. Thank you in any case for your effort.

**Comment by qwerdee** [comment]
I ran into this as well, would be amazing to have this merged

**Comment by szepeviktor** [comment]
Those void errors are because of phpstan/phpstan (1.10.50)

**Comment by Brenneisen** [comment]
Yes it seems to be unrelated to this issue.

**Comment by Brenneisen** [comment]
I have added a PR (https://github.com/larastan/larastan/pull/1802) to solve this problem.

**Comment by Brenneisen** [comment]
@szepeviktor @canvural @nunomaduro What is the problem that this is not moving forward? Other PRs (including mine) have already been merged in the meantime. Larastan has been throwing an internal error since the last version. Would it be possible to merge the PR as soon as possible and make a new release?

**Comment by szepeviktor** [comment]
I was told not to create releases.

**Comment by Brenneisen** [comment]
@canvural @nunomaduro Can you please take a look and do a review? We really need the fix urgently. It would be great if we could make some progress here.

**Comment by Brenneisen** [comment]
@canvural @CanVuralStudocu @nunomaduro Please excuse me for asking again, but I have not received any reply for the last two weeks. Can you please take a look and do a review?

**Comment by canvural** [comment]
I'll check it when I have time.

**Comment by Brenneisen** [comment]
Rebased.

**Comment by canvural** [comment]
Thank you!

**Pull request merged**
