### PR TITLE
Use PHPStan 2.0

### PR DESCRIPTION
**Pull request by szepeviktor**
👉🏻 3.x

### CODE REVIEW

**Comment by canvural** [comment]
Oh wow, this is dependency hell 😢 Can we workaround somehow? 🤔

**Comment by szepeviktor** [comment]
This may be enough: https://github.com/rectorphp/rector/issues/8815

**Comment by canvural** [comment]
> This may be enough: [rectorphp/rector#8815](https://github.com/rectorphp/rector/issues/8815)

I don't think they will do it soon. It's a huge change. Also they'll need to release Rector 2.0, then `spatie/laravel-ray` needs to update their code and then `workbench` needs to update their code.. So we need another solution for now. I'll think about it.

**Comment by canvural** [comment]
We can add
```json
"replace": {
  "rector/rector": "*"
},
```

just before installing the dependencies 🤷🏽 Very ugly hack

**Comment by canvural** [comment]
Fixed in the branch.

**Pull request closed without merging**
