### PR TITLE
Add version constrain for PHPStan <1.3

### PR DESCRIPTION
**Pull request by szepeviktor**
As we have multiple issues.

### CODE REVIEW

**Comment by nunomaduro** [comment]
@szepeviktor Can you elaborate?

**Comment by szepeviktor** [comment]
#1073 #1077 #1078

**Review by williamdes — CHANGES_REQUESTED** [review]
Can we do better and have a newer phpstan ?

**Comment by szepeviktor** [comment]
@nunomaduro One more: https://github.com/szepeviktor/larastan-issue/pull/1

**Comment by nunomaduro** [comment]
@canvural is currently working on Larastan v2, and we will tackle this after.

**Comment by rcerljenko** [comment]
oh nice! any release eta yet for v2?

**Comment by rcerljenko** [comment]
happy to report that the problem fixed istelf with the new phpstan 1.4 update! yey!

https://github.com/phpstan/phpstan/releases/tag/1.4.0

**Comment by szepeviktor** [comment]
I think we need to resolve the problem with 1.3

**Comment by szepeviktor** [comment]
Another one: https://github.com/nunomaduro/larastan/runs/4861060746?check_suite_focus=true

**Comment by canvural** [comment]
None of the linked issues are directly related to PHPStan 1.3 so I'm closing this.

**Pull request closed without merging**
