### PR TITLE
chore: run integration tests parallel to normal tests

### PR DESCRIPTION
**Pull request by canvural**
//

### CODE REVIEW

**Comment by szepeviktor** [comment]
May I create a tiny repo for this purpose?

**Comment by canvural** [comment]
> May I create a tiny repo for this purpose?

For what exactly?

Anyway, currently integration tests workflow runs only tests are green, but is not shown in the PR checks. I read some stuff online and there is no workaround that. So I think I'll convert it to just run parallel.

**Comment by szepeviktor** [comment]
> there is no workaround

Very worring.

---

kép

:)

**Comment by szepeviktor** [comment]
I do not have the strength to argue.
Here we have a naming mismatch. These are E2E tests, not integrations tests.

**Pull request merged**
