### PR TITLE
fix: model select not checking model properties

### PR DESCRIPTION
**Pull request by clementbirkle**
This PR fix this issue with "select" method: https://github.com/larastan/larastan/issues/1824

### CODE REVIEW

**Comment by calebdw** [comment]
I already tried this and it didn't work because the query builder doesn't know about the model generics (you haven't passed any model to `model-property`, like `model-property<static>`).

I suspect that if you added a test that should pass that it would fail:

```php
\App\User::query()->select('email');
```

**Comment by clementbirkle** [comment]
I just tested with your example and the test passed.

You're probably right...

**Comment by calebdw** [comment]
Interesting---if it work it works, but I'm not sure how :upside_down_face: 

Can probably also do the same for `addSelect`

**Comment by clementbirkle** [comment]
I tested it in the real world, and yes, you are correct; it doesn't work. I'm canceling this PR.

**Pull request closed without merging**
