### PR TITLE
Fixed compatibility with PHPStan 0.11.13

### PR DESCRIPTION
**Pull request by ondrejmirtes**
This is about: https://github.com/phpstan/phpstan/issues/2361

Please release this change. Thank you.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Should we raise the phpstan dependency version to 0.11.13?

**Comment by ondrejmirtes** [comment]
Not necessary.

**Comment by ondrejmirtes** [comment]
@nunomaduro Can you please tag a new 0.3.19 release with this change? People are reporting this error a lot :) Thank you!

**Comment by szepeviktor** [comment]
Waiting for #295

**Comment by ondrejmirtes** [comment]
No, that doesn't make sense :( Nuno said "After this feature we need to release a major version."

So if you tagged dev-master now, it would get to all users, no need to wait for additional blocking work. I'd realliy appreciate this.

**Comment by szepeviktor** [comment]
I am just a janitor here, I don't even have a release checklist.

**Comment by nunomaduro** [comment]
@ondrejmirtes Thanks for heads up, the version `v0.3.19` is out.

**Pull request merged**
