### PR TITLE
Add stub files to CS config

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by szepeviktor** [comment]
👀 

kép

**Comment by szepeviktor** [comment]
@GrahamCampbell Could you help us?

**Comment by GrahamCampbell** [comment]
Those stub files are not valid PHP syntax, thus are crashing php-cs-fixer.

**Comment by GrahamCampbell** [comment]
Specifically, it's the class attributes separation, which makes sense given the functions are missing their bodies. You could try turning that off.

**Comment by szepeviktor** [comment]
Thank you.

**Pull request closed without merging**
