### PR TITLE
Type generalization precision is now required

### PR DESCRIPTION
**Pull request by szepeviktor**
https://github.com/phpstan/phpstan-src/commit/65681033ff625c67a478212a0cd6da29cd5ab5fa

I think no documentation is needed.

@canvural Please wait for the next PHPStan release.

### CODE REVIEW

**Comment by canvural** [comment]
Thanks! Can you change the target branch to phpstan-1.0? In that branch I'm fixing the compatibility with the PHPStan 1.0

**Comment by szepeviktor** [comment]
Changing base 👉 disaster :)

**Comment by szepeviktor** [comment]
@canvural Please cherry-pick my commit or simply copy-paste these lines.

**Comment by szepeviktor** [comment]
Done.
https://github.com/nunomaduro/larastan/commits/phpstan-1.0

**Pull request closed without merging**
