### PR TITLE
fix: check php version before accessing isEnum

### PR DESCRIPTION
**Pull request by calebdw**
Not sure why ci started failing, but this should hopefully fix it...

### CODE REVIEW

**Comment by calebdw** [comment]
So PHP 8.0.6 is installed in the ci, but it's still passing the version check?

**Comment by szepeviktor** [comment]
> So PHP 8.0.6 is installed in the ci, but it's still passing the version check?

This is a custom `ReflectionProvider`
https://github.com/phpstan/phpstan-src/blob/1.11.x/src/Reflection/ReflectionProvider.php

**Comment by calebdw** [comment]
The error message is: `Error: Call to undefined method ReflectionClass::isEnum()`, if it were the custom reflection provider then it would be `Error: Call to undefined method PHPStan\Reflection\ClassReflection::isEnum()`.

However, that still doesn't explain:
1. why it suddenly started failing in the first place
2. the `isEnum()` call is still behind a version check so shouldn't be called
3. the `isEnum()` call works on PHP 8.1 tests

**Comment by calebdw** [comment]
@ondrejmirtes, something was introduced in PHPStan 1.10.61 that is causing this run to fail:

https://github.com/larastan/larastan/actions/runs/8397529980/job/23000977060?pr=1882

I pinned phpstan at 1.10.60 and the job does not fail (however, job fails up to the latest version 1.10.64).

**Comment by calebdw** [comment]
This commit might fix the job?

https://github.com/phpstan/phpstan-src/commit/4c167d7ff11dee9122a298ab0eb941ac61bb2ff1

**Comment by ondrejmirtes** [comment]
This is a bug that's purely in PHPStan, you don't need to do anything in Larastan to work around that, I'm going to fix it.

**Comment by ondrejmirtes** [comment]
The fix:

* https://github.com/ondrejmirtes/BetterReflection/commit/94ca1336c58332604a74012d20286a240db376ea

It's going to be released in PHPStan 1.10.65 soon.

**Comment by ondrejmirtes** [comment]
Let's try this: https://github.com/phpstan/phpstan/releases/tag/1.10.65

**Comment by calebdw** [comment]
Thanks Ondre!

**Pull request closed without merging**
